manifest:
  defaults:
    name: zmk
    import: app/west.yml
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: ftc
      url-base: https://github.com/ftc
  projects:
    - remote: zmkfirmware
      revision: main
    - remote: ftc
      revision: mouse-ftc
  self:
    path: config
