# https://docs.zephyrproject.org/latest/develop/west/manifest.html
# main: zmkfirmware:main
# urob:mouse-3.2
# ftc:mouse-ftc
# PR 2027: petejohanson:feat/pointers-move-scroll
---
manifest:
  defaults:
    remote: petejohanson
    revision: feat/pointers-move-scroll
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: petejohanson
      url-base: https://github.com/petejohanson
  projects:
    - name: upstream
      remote: zmkfirmware
      repo-path: zmk
      revision: main
      import: app/west.yml
      clone-depth: 1
    - name: overlay
      repo-path: zmk
      import: app/west.yml
      clone-depth: 1
  self:
    path: config
