# https://docs.zephyrproject.org/latest/develop/west/manifest.html
# main: zmkfirmware:main
# urob:mouse-3.2
# ftc:mouse-ftc
# PR 2027: petejohanson:feat/pointers-move-scroll
---
manifest:
  defaults:
    remote: pete
    revision: feat/pointers-move-scroll
  remotes:
    - name: pete
      url-base: https://github.com/petejohanson
  projects:
    - name: zmk
      import: app/west.yml
      clone-depth: 1
  self:
    path: config
